name: Improved Streaming Build

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout plugin-sdk
        uses: actions/checkout@v6
        with:
          repository: DK22Pac/plugin-sdk
          path: plugin-sdk

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Generate plugin-sdk projects
        shell: cmd
        run: |
          set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\plugin-sdk
          "%PLUGIN_SDK_DIR%\tools\premake\premake5" vs2022 --file="%PLUGIN_SDK_DIR%\tools\premake\premake5.lua"

      - name: Build plugin-sdk
        shell: cmd
        run: |
          set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\plugin-sdk
          msbuild "%PLUGIN_SDK_DIR%\plugin.sln" /p:Configuration=Release /p:Platform="Mixed Platforms" /t:Plugin_SA /m

      - name: Build
        shell: cmd
        run: |
          set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\plugin-sdk
          msbuild LoadWholeMap.sln /p:Configuration="GTASA Release" /p:Platform=x86

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: LoadWholeMap-GTASA
          path: output/
